<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Properties\Challenge.Assemblies.snk</AssemblyOriginatorKeyFile>
    <Configurations>Release;Debug</Configurations>
    <Platforms>x64</Platforms>
    <IsPackable>false</IsPackable>
    <DocumentationFile>bin\x64\Debug\Challenge.Attributes.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Challenge.Attributes.csproj.DotSettings" />
  </ItemGroup>

</Project>
