<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Properties\Challenge.Maths.snk</AssemblyOriginatorKeyFile>
    <Configurations>Release;Debug</Configurations>
    <Platforms>x64</Platforms>
    <DocumentationFile>bin\x64\Debug\Challenge.Maths.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(CI)' == 'true' ">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="JetBrains.ExternalAnnotations" Version="10.2.170" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Challenge.Utils\Challenge.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Challenge.Maths.csproj.DotSettings" />
  </ItemGroup>

</Project>
