<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <RootNamespace>Challenge.Generator</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <Configurations>Release;Debug</Configurations>
    <DocumentationFile>bin\Debug\Challenge.Generator.xml</DocumentationFile>
    <AssemblyOriginatorKeyFile>Properties\Challenge.Generator.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsRoslynComponent>true</IsRoslynComponent>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <PackageOutputPath>..\Packages</PackageOutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Challenge.Generator</PackageId>
    <Title>Challenge Generator</Title>
    <Authors>ChrisViral</Authors>
    <Owner>ChrisViral</Owner>
    <Description>Challenge solver source generator</Description>
    <Copyright>Copyright © 2026 Christophe Savard</Copyright>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/ChrisViral/ChallengeLibraries</RepositoryUrl>
    <PackageTags>Advent of Code,Code Challenge,Source Generator</PackageTags>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup>
    <BuildYear>$([System.DateTime]::UtcNow.ToString("yyyy"))</BuildYear>
    <BuildMonth>$([System.DateTime]::UtcNow.ToString("MM"))</BuildMonth>
    <MonthStart>$([System.DateTime]::Parse($([System.DateTime]::UtcNow.ToString("yyyy-MM-01"))))</MonthStart>
    <MonthHours>$([System.Math]::Floor($([System.DateTime]::UtcNow.Subtract($(MonthStart)).TotalHours)))</MonthHours>
    <DayMinutes>$([System.Math]::Floor($([System.DateTime]::UtcNow.Subtract($([System.DateTime]::UtcNow.Date)).TotalMinutes)))</DayMinutes>
    <Version>$(BuildYear).$(BuildMonth).$(MonthHours).$(DayMinutes)</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(CI)' == 'true' ">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup>
    <PackageScribanIncludeSource>true</PackageScribanIncludeSource>
    <PolySharpIncludeRuntimeSupportedAttributes>true</PolySharpIncludeRuntimeSupportedAttributes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="JetBrains.ExternalAnnotations" Version="10.2.170" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.9.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <PackageReference Include="Scriban" Version="7.5.0" IncludeAssets="Build" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
    <PackageReference Include="PolySharp" Version="1.16.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Test\**\*"/>
    <None Remove="Test\**\*"/>
    <None Include="README.md" Pack="true" PackagePath="$(PackageReadmeFile)" />
    <None Remove="Challenge.Generator.csproj.DotSettings" />
    <EmbeddedResource Include="Templates\**\*.sbn" />
    <Compile Include="..\Challenge.Solvers\NameExport.cs" Link="Imported\NameExport.cs" />
    <None Include="$(OutputPath)\$(AssemblyName).dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
  </ItemGroup>

</Project>
