<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Properties\Challenge.CLI.snk</AssemblyOriginatorKeyFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <PlatformTarget>x64</PlatformTarget>
    <DocumentationFile>bin\Debug\Challenge.CLI.xml</DocumentationFile>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DocumentationFile>bin\Release\Challenge.CLI.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions.Analyzers" Version="1.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="CSharpFunctionalExtensions.StrongName" Version="3.7.0" />
    <PackageReference Include="DotMake.CommandLine" Version="3.7.0" />
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="JetBrains.ExternalAnnotations" Version="10.2.170" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Challenge.CLI.csproj.DotSettings" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Challenge.Solvers\Challenge.Solvers.csproj" />
  </ItemGroup>

</Project>
