<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Properties\Challenge.Solvers.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="JetBrains.ExternalAnnotations" Version="10.2.170" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Challenge.Collections\Challenge.Collections.csproj" />
    <ProjectReference Include="..\Challenge.Utils\Challenge.Utils.csproj" />
  </ItemGroup>

</Project>
